apiVersion: v1
kind: Service

metadata:
  name: food-app-service

spec:
  selector:
    app: food-app

  type: NodePort

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
